import turtle
def Achar(pen,x,y):
    pen.pendown()
    pen.penup()
    pen.goto(x,y)
    pen.pendown()
    c1 = turtle.Pen()
    c1.width(3)
    c1.color("orange")
    c1.speed(1)
    c1.hideturtle()
    pen.speed(2)
    pen.left(65)
    pen.forward(4900**0.5)
    pen.right(130)
    pen.forward(4900**0.5)
    c1.penup()
    c1.goto(x + 15, y + 30)
    c1.pendown()
    c1.forward(30)
    pen.left(65)
    pen.penup()
    pen.forward(25)
    pen.pendown()

    a,b = pen.pos()
    return a,b

def Bchar(pen,x,y):
    pen.pendown()
    pen.left(90)
    pen.forward(65)
    pen.left(90)
    pen.circle(15,-180)
    pen.left(180)
    pen.circle(18,-180)
    pen.penup()
    pen.forward(43)
    pen.pendown()
    a, b = pen.pos()
    return a, b

def Cchar(pen,x,y):
    pen.pendown()
    pen.penup()
    pen.forward(32.5)
    pen.pendown()
    pen.forward(5)
    a1,b1 = pen.pos()
    pen.penup()
    pen.forward(-5)
    pen.pendown()
    pen.circle(32.5,-180)
    pen.forward(-5)
    pen.penup()
    pen.goto(a1+25,b1)
    a, b = pen.pos()
    pen.left(180)
    pen.pendown()
    return a, b

def Dchar(pen,x,y):
    pen.pendown()
    pen.left(90)
    pen.forward(65)
    pen.right(150)
    pen.forward(75)
    pen.right(120)
    pen.forward(75/2)
    pen.penup()
    pen.forward(-(75/2+25))
    pen.right(180)
    pen.pendown()
    a, b = pen.pos()
    return a, b

def Echar(pen,x,y):
    pen.pendown()
    pen.forward(40)
    a1,b1 = pen.pos()
    pen.penup()
    pen.forward(-40)
    pen.pendown()
    pen.left(90)
    pen.forward(32.5)
    pen.right(90)
    pen.forward(30)
    pen.penup()
    pen.forward(-30)
    pen.pendown()
    pen.left(90)
    pen.forward(32.5)
    pen.right(90)
    pen.forward(40)
    pen.penup()
    pen.forward(-40)
    pen.pendown()
    pen.left(90)
    pen.penup()
    pen.goto(a1,b1)
    pen.right(90)
    pen.forward(25)
    pen.pendown()
    a, b = pen.pos()
    return a, b

def Fchar(pen,a,b):
    pen.pendown()
    pen.left(90)
    pen.forward(32.5)
    pen.right(90)
    pen.forward(30)
    pen.penup()
    pen.forward(-30)
    pen.pendown()
    pen.left(90)
    pen.forward(32.5)
    pen.right(90)
    pen.forward(40)
    pen.penup()
    pen.forward(-40)
    pen.pendown()
    pen.left(90)
    pen.penup()
    pen.right(90)
    pen.goto(a+65,b)
    pen.pendown()
    a, b = pen.pos()
    return a, b

def Gchar(pen,a,b):
    pen.pendown()
    pen.penup()
    pen.forward(32.5)
    pen.pendown()
    pen.forward(5)
    a1,b1 = pen.pos()
    pen.penup()
    pen.forward(-5)
    pen.pendown()
    pen.circle(32.5,-180)
    pen.forward(-5)
    pen.penup()
    pen.goto(a+20,b+20)
    pen.pendown()
    pen.forward(-19)
    pen.left(90)
    pen.forward(20)
    pen.penup()
    pen.goto(a1 + 25, b1)
    a, b = pen.pos()
    pen.left(90)
    pen.pendown()
    return a, b

def Hchar(pen,a,b):
    pen.pendown()
    pen.speed(1)
    pen.left(90)
    pen.forward(65)
    pen.penup()
    pen.forward(-32.5)
    pen.pendown()
    pen.right(90)
    pen.forward(40)
    pen.left(90)
    pen.forward(32.5)
    pen.penup()
    pen.forward(-32.5)
    pen.pendown()
    pen.forward(-32.5)
    pen.right(90)
    pen.penup()
    pen.forward(25)
    a,b = pen.pos()
    return a,b

def Ichar(pen,a,b):
    pen.pendown()
    pen.left(90)
    pen.forward(65)
    pen.penup()
    pen.forward(13)
    pen.pendown()
    pen.circle(1)
    pen.penup()
    pen.hideturtle()
    pen.forward(-78)
    pen.right(90)
    pen.forward(25)
    pen.pendown()
    pen.showturtle()
    a, b = pen.pos()
    return a, b

def Jchar(pen,a,b):
    pen.pendown()
    x,y = pen.pos()
    pen.right(90)
    pen.penup()
    pen.forward(-18)
    pen.pendown()
    pen.circle(18,180)
    pen.forward(47)
    a = x+65
    b = y
    pen.penup()
    pen.goto(a,b)
    pen.right(90)
    pen.pendown()
    return a, b

def Kchar(pen,a,b):
    pen.pendown()
    pen.left(90)
    pen.forward(65)
    pen.penup()
    pen.forward(-32.5)
    pen.right(45)
    pen.pendown()
    pen.forward(45.96)
    pen.penup()
    pen.forward(-45.96)
    pen.pendown()
    pen.right(90)
    pen.forward(45.90)
    pen.penup()
    pen.left(45)
    pen.forward(25)
    pen.pendown()
    a, b = pen.pos()
    return a, b

def Lchar(pen,a,b):
    pen.pendown()
    pen.left(90)
    pen.forward(65)
    pen.penup()
    pen.forward(-65)
    pen.pendown()
    pen.right(90)
    pen.forward(35)
    pen.penup()
    pen.forward(25)
    a, b = pen.pos()
    return a, b

def Mchar(pen,a,b):
    pen.pendown()
    pen.left(90)
    pen.forward(65)
    pen.right(90)
    pen.right(53)
    pen.forward(30)
    pen.left(106)
    pen.forward(30)
    pen.right(143)
    pen.forward(65)
    pen.left(90)
    pen.penup()
    pen.forward(25)
    a, b = pen.pos()
    return a, b

def Nchar(pen,a,b):
    pen.pendown()
    pen.left(90)
    pen.forward(65)
    pen.right(143)
    pen.forward(81.25)
    pen.left(143)
    pen.forward(65)
    pen.penup()
    pen.forward(-65)
    pen.right(90)
    pen.forward(25)
    pen.pendown()
    a, b = pen.pos()
    return a, b

def Ochar(pen,a,b):
    pen.speed(1)
    pen.pendown()
    pen.penup()
    pen.forward(5)  # colt
    pen.pendown()
    pen.forward(30)
    pen.left(45)
    pen.forward(7)  # colt
    pen.left(45)
    pen.forward(55)
    pen.left(45)
    pen.forward(7)  # colt
    pen.left(45)
    pen.forward(30)
    pen.left(45)
    pen.forward(7)  # colt
    pen.left(45)
    pen.forward(55)
    pen.left(45)
    pen.forward(7)  # colt
    pen.left(45)
    pen.penup()
    pen.forward(60)
    a, b = pen.pos()
    a, b = pen.pos()
    return a, b

def Pchar(pen,a,b):
    pen.pendown()
    pen.left(90)
    pen.forward(25)
    pen.right(90)
    pen.forward(7)
    pen.circle(20,180)
    pen.forward(7)
    pen.left(90)
    pen.forward(65)
    pen.left(90)
    pen.penup()
    pen.forward(45)
    pen.pendown()
    a, b = pen.pos()
    return a, b

def Rchar(pen,a,b):
    pen.pendown()
    pen.left(90)
    pen.forward(25)
    pen.right(90)
    pen.forward(7)
    pen.circle(20,180)
    pen.forward(7)
    pen.left(90)
    pen.forward(40)
    pen.left(47)
    pen.forward(36.79)
    pen.left(43)
    pen.penup()
    pen.forward(25)
    pen.pendown()
    a, b = pen.pos()
    return a, b

def Schar(pen,a,b):
    pen.pendown()
    pen.left(90)
    pen.penup()
    pen.forward(20)
    pen.pendown()
    pen.left(180)
    pen.circle(20, 180)
    pen.left(90-31.14)
    pen.forward(47.16)
    pen.right(90-31.14)
    pen.left(180)
    pen.circle(20, -180)
    pen.penup()
    pen.left(180)
    pen.forward(45)
    pen.left(90)
    pen.forward(25)
    a, b = pen.pos()
    return a, b

def Tchar(pen,a,b):
    pen.pendown()
    pen.penup()
    pen.forward(20)
    pen.pendown()
    pen.left(90)
    pen.forward(65)
    pen.left(90)
    pen.forward(20)
    pen.left(180)
    pen.forward(40)
    pen.penup()
    pen.right(90)
    pen.forward(65)
    pen.left(90)
    pen.forward(25)
    pen.pendown()
    a, b = pen.pos()
    return a, b

def Uchar(pen,a,b):
    pen.pendown()
    pen.left(90)
    pen.penup()
    pen.forward(20)
    pen.pendown()
    pen.forward(45)
    pen.forward(-45)
    pen.left(180)
    pen.circle(20, 180)
    pen.forward(45)
    pen.forward(-45)
    pen.penup()
    pen.forward(-20)
    pen.right(90)
    pen.forward(25)
    pen.pendown()
    a, b = pen.pos()
    return a, b

def Vchar(pen,a,b):
    pen.pendown()
    pen.penup()
    pen.forward(20)
    pen.pendown()
    pen.left(110)
    pen.forward(68)
    pen.forward(-68)
    pen.right(40)
    pen.forward(68)
    pen.forward(-68)
    pen.right(70)
    pen.penup()
    pen.forward(45)
    pen.pendown()
    a, b = pen.pos()
    return a, b

def Xchar(pen,a,b):
    pen.pendown()
    pen.left(45)
    pen.forward(91.92)
    pen.forward(-91.92/2)
    pen.left(90)
    pen.forward(91.92/2)
    pen.forward(-91.92)
    pen.pendown()
    a, b = pen.pos()
    return a, b

def Ychar(pen,a,b):
    pen.pendown()
    pen.penup()
    pen.forward(30)
    pen.left(90)
    pen.pendown()
    pen.forward(40)
    pen.left(45)
    pen.forward(35.35)
    pen.forward(-35.35)
    pen.right(90)
    pen.forward(35.35)
    pen.right(135)
    pen.penup()
    pen.forward(65)
    pen.penup()
    pen.left(90)
    pen.forward(25)
    pen.pendown()
    a, b = pen.pos()
    return a, b

def Zchar(pen,a,b):
    pen.pendown()

    pen.forward(27)
    pen.forward(-27)
    pen.left(90-18.37)
    pen.forward(68)
    pen.left(90+18.37)
    pen.forward(27)
    pen.penup()
    pen.forward(-34)
    pen.left(90)
    pen.forward(65)
    pen.left(90)
    pen.forward(25)
    #pen.forward(25)
    pen.pendown()
    a, b = pen.pos()
    return a, b

def intrebarechar(pen,a,b):
    pen.pendown()
    x,y = pen.pos()
    pen.left(90)
    pen.penup()
    pen.forward(45)
    pen.pendown()
    # pen.left(180)
    pen.circle(-20,180)
    for i in range(8):
        pen.right(10)
        pen.forward(4)
    pen.left(80)
    pen.forward(10)
    pen.penup()
    pen.forward(20)
    pen.pendown()
    pen.circle(1)
    a = x+65
    b=y
    pen.penup()
    pen.left(90)
    pen.goto(a,b)
    return a,b

def exclamarechar(pen,a,b):
    pen.pendown()
    pen.circle(1)
    pen.begin_fill()
    pen.circle(1)
    pen.end_fill()
    pen.left(90)
    pen.penup()
    pen.forward(19)
    pen.pendown()
    pen.forward(45)
    pen.left(180)
    pen.penup()
    pen.forward(65)
    pen.left(90)
    pen.forward(25)
    a,b= pen.pos()
    return a,b

def punctchar(pen,a,b):
    pen.pendown()
    pen.begin_fill()
    pen.circle(2)
    pen.end_fill()
    pen.penup()
    pen.forward(25)
    a,b = pen.pos()
    return a,b

def spatiuchar(pen,a,b):
    pen.penup()
    pen.forward(50)
    pen.pendown()
    a,b = pen.pos()
    return a,b
